### PR TITLE
Improve deprecation warnings wrt #209

### PR DESCRIPTION
**Pull request by hasufell**
@tbidne can you test this?

Something else I noticed: building filepath itself throws many deprecation warnings. Can we ignore all those package internal deprecation warnings somehow without causing a lot of work?

### CODE REVIEW

**Comment by tbidne** [comment]
> @tbidne can you test this?

It works on my test repo: No errors for using `EncodingException` [here](https://github.com/tbidne/osstr-deprecated/tree/211). Given this PR is for only the single module `System.OsPath.Encoding.Internal.hs`, I presume the other deprecated modules are intended to deprecate everything.

> Something else I noticed: building filepath itself throws many deprecation warnings. Can we ignore all those package internal deprecation warnings somehow without causing a lot of work?

Well, you can throw `-Wno-deprecations` in the affected modules for as long as you have to use the deprecated symbols. Otherwise you can use [@Bodigrim's trick](https://github.com/haskell/filepath/issues/209#issuecomment-1832809252) with the hidden modules + deprecated re-exports. But this is a decent amount of work, especially with the tricky cpp.

**Comment by Bodigrim** [comment]
Better than status quo, but I'd go for the trick https://github.com/haskell/filepath/issues/209#issuecomment-1832809252: move the content of `System.OsPath.Encoding.Internal` to `other-module` `System.OsPath.Encoding.Hidden`, without deprecations. Then `System.OsPath.Encoding.Internal` reexports `System.OsPath.Encoding.Hidden` and adds a module-wide deprecation atop, and other modules of `filepath` rely on `System.OsPath.Encoding.Hidden` directly. This way you don't have to disable `-Wno-deprecations` everywhere, and it works with all GHC versions.

**Comment by tbidne** [comment]
> Better than status quo, but I'd go for the trick [#209 (comment)](https://github.com/haskell/filepath/issues/209#issuecomment-1832809252): move the content of `System.OsPath.Encoding.Internal` to `other-module` `System.OsPath.Encoding.Hidden`, without deprecations. Then `System.OsPath.Encoding.Internal` reexports `System.OsPath.Encoding.Hidden` and adds a module-wide deprecation atop, and other modules of `filepath` rely on `System.OsPath.Encoding.Hidden` directly. This way you don't have to disable `-Wno-deprecations` everywhere, and it works with all GHC versions.

Here's what that looks like (I split the [commits](https://github.com/tbidne/filepath/commits/deprecate-hidden) on my branch to make the diff easier):

1. The [first commit](https://github.com/tbidne/filepath/commit/8a99a56b612614c60b02245066d763b06de07982) simply renames the deprecated modules `X.hs -> X.Hidden.hs`.

2. The [second commit](https://github.com/tbidne/filepath/commit/07762b6c6600b2c6d6b41031300ac8a717f39636) copies the API from `X.Hidden.hs` to deprecated `X.hs`.

**Comment by hasufell** [comment]
@tbidne can you open a PR?

**Comment by tbidne** [comment]
https://github.com/haskell/filepath/pull/213

**Comment by hasufell** [comment]
superseded by https://github.com/haskell/filepath/pull/213

**Pull request closed without merging**
