### PR TITLE
GHCJS patches.

### PR DESCRIPTION
**Pull request by alexanderkjeldaas**
Patches from the GHCJS project.

### CODE REVIEW

**Comment by ndmitchell** [comment]
I discussed patches very similar to these in https://github.com/haskell/filepath/issues/13. My view is that if GHCJS wants to know whether its on Windows or Linux, System.Info is the right place to ask. Having `isWindows` in `FilePath` seems like it's going to be massively abused. I am a big fan of having `isWindows` in System.Info, and it's in my extra library: https://hackage.haskell.org/package/extra-1.6.6/docs/Extra.html#v:isWindows

**Comment by alexanderkjeldaas** [comment]
Added Current.

**Comment by ndmitchell** [comment]
Two concrete questions:

* Why export isWindows/isPosix? Could we avoid that?

* Why introduce `Current`. We have `System.FilePath` which is meant to be the current path, why not have that one be dynamic switching on Javascript?

**Comment by alexanderkjeldaas** [comment]
@luite  comments?  Is any of that needed?

**Comment by ndmitchell** [comment]
Given this has been a long time, I'm going to close the PR. As before, I don't think this ever belonged in filepath, and should go to the base library via the standard approvals process.

**Pull request closed without merging**
