### PR TITLE
other-extensions hygiene

### PR DESCRIPTION
**Pull request by hvr**

### CODE REVIEW

**Comment by ndmitchell** [comment]
Thanks. Should Safe be on that list? I see it declared as an extension in the Internal module. (My personal feeling is that `Safe` is a poorly designed infection that breeds in Haskell code and should be deleted from the language to be replaced with real OS level sandboxing - but I appreciate the CLC seem to feel differently, so I leave others to massage the Safe annotations in filepath.)

**Comment by ndmitchell** [comment]
Oh, and I typically view OtherExtensions as poor hygiene, since then you don't have to list them in each module, and can use them without it being clear in the source. But if you like it this way, I don't really mind.

**Comment by hvr** [comment]
@ndmitchell the reasoning is, that starting with  Cabal 1.24 will consider `other-extensions` like a build-dependency in its solver. This will allow us to avoid the hack using the `base`-version as a proxy for declaring required compiler features... :-)

**Comment by rwbarton** [comment]
> Oh, and I typically view OtherExtensions as poor hygiene, since then you don't have to list them in each module, and can use them without it being clear in the source. But if you like it this way, I don't really mind.

`default-extensions` are the ones that are automatically enabled in every module of the package. `other-extensions` are just ones that you (might) use in one or more modules explicitly with LANGUAGE flags. See for instance https://github.com/haskell/cabal/issues/1517#issuecomment-46843791.

**Comment by ndmitchell** [comment]
Thanks @rwbarton - that's a lot less problematic.

**Comment by ndmitchell** [comment]
For info, Safe is on that list, just in a conditional on ghc-7.2 section, so not immediately adjacent.

**Pull request merged**
