### PR TITLE
Simplify indexWord8Array and writeWord16Array

### PR DESCRIPTION
**Pull request by Bodigrim**

### CODE REVIEW

**Comment by Bodigrim** [comment]
Sigh. I can conjure up CPP to support GHC < 8.6, but at that point it would no longer be a simplification.

**Comment by hasufell** [comment]
This will go into the new [os-string](https://github.com/haskell/os-string). I think we also dropped ghc < 8.6 in unix, didn't we?

**Comment by Bodigrim** [comment]
> I think we also dropped ghc < 8.6 in unix, didn't we?

According to https://github.com/haskell/unix/blob/4386d8210ce36f512436a6b522051b858b31823d/unix.cabal, yes, we did. 

If you decide to drop GHC < 8.6 in `os-string`, I'll re-raise this PR against it. Or feel free to cherry-pick yourself, this should be good to go as is.

**Comment by hasufell** [comment]
>If you decide to drop GHC < 8.6 in os-string

Yeah, we can do that.

**Comment by hasufell** [comment]
continued here: https://github.com/haskell/os-string/pull/3

**Pull request closed without merging**
